plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.0'
}

group = 'org.KillerYT'
version = '0.0.2-beta-8'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        name = "papermc"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "placeholderapi"
        url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
    }
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT"
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    compileOnly 'me.clip:placeholderapi:2.11.6'

    // Используем локальный JAR
    implementation files('libs/KillerCoreAPI-1.0.0.jar')
    // Удалите или закомментируйте следующую строку:
    // implementation 'org.killeryt:KillerCoreAPI:1.0-SNAPSHOT'

    // VaultAPI для надёжности (если в ядре compileOnly)
    implementation('com.github.MilkBowl:VaultAPI:1.7') {
        exclude group: 'org.bukkit', module: 'bukkit'
    }

    compileOnly 'net.md-5:bungeecord-chat:1.20-R0.2'
}

processResources {
    filesMatching("paper-plugin.yml") {
        expand(version: project.version)
    }
    filteringCharset = 'UTF-8'
}

shadowJar {
    archiveBaseName.set('RegionMC')
    archiveVersion.set(project.version)
    archiveClassifier.set('')
    mergeServiceFiles()
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
}

build {
    dependsOn shadowJar
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}